excluded_targets:
  - flash_xip               # exclude the flash_xip target for core1
  - flash_xip_release       # exclude the flash_xip_release target for core1
  - flash_sdram_xip         # exclude the flash_sdram_xip target for core1
  - flash_sdram_xip_release # exclude the flash_sdram_xip_release target for core1
  - flash_uf2
debug:
    ses:
      auto_start_gdb_server: true
      gdb_server_port: 3333
dependency:
  - multicore
